##Deep Reinforcement Learning - Grid World Environment Simulation'
Prof.Eranki.L.N.Kiran Kumar

In [1]:
 import numpy as np

def value_iteration_with_math():
    rows, cols = 3, 4
    discount = 0.9
    noise = 0.2

    # Grid Setup
    V = np.zeros((rows, cols))
    terminal = {(0, 3): 1.0, (1, 3): -1.0}
    obstacle = (1, 1)

    try:
        k_iterations = int(input("Enter the number of iterations (k): "))
    except ValueError:
        k_iterations = 3


    for k in range(1, k_iterations + 1):
        new_V = np.copy(V)

        # We will specifically "Trace" the math for cell (0, 2)
        # Assuming the 'Right' action is chosen for (0, 2)
        r, c = 0, 2
        # Probabilities: 0.8 (East), 0.1 (North-hit wall), 0.1 (South-hit (1,2))
        intended_val = 0.8 * (0 + discount * 1.0) # Move East to Exit
        slip_north = 0.1 * (0 + discount * V[0, 2]) # Hit top wall, stay
        slip_south = 0.1 * (0 + discount * V[1, 2]) # Move to (1, 2)

        trace_math = f"V_{k}(0,2) = max_a [ 0.8*({discount}*V_{k-1}(0,3)) + 0.1*({discount}*V_{k-1}(0,2)) + 0.1*({discount}*V_{k-1}(1,2)) ]"

        # Standard Iteration Loop
        for r_idx in range(rows):
            for c_idx in range(cols):
                if (r_idx, c_idx) in terminal:
                    new_V[r_idx, c_idx] = terminal[(r_idx, c_idx)]
                    continue
                if (r_idx, c_idx) == obstacle: continue

                # Check all 4 actions
                best_v = -float('inf')
                for dr, dc in [(-1,0), (1,0), (0,1), (0,-1)]:
                    # Simple noise logic for calculation
                    if (dr, dc) == (0, 1): # East
                        # 0.8 East, 0.1 North, 0.1 South
                        moves = [(0,1), (-1,0), (1,0)]
                    elif (dr, dc) == (0, -1): # West
                        moves = [(0,-1), (-1,0), (1,0)]
                    elif (dr, dc) == (-1, 0): # North
                        moves = [(-1,0), (0,-1), (0,1)]
                    else: # South
                        moves = [(1,0), (0,-1), (0,1)]

                    ev = 0
                    probs = [0.8, 0.1, 0.1]
                    for i, (tr, tc) in enumerate(moves):
                        nr, nc = r_idx + tr, c_idx + tc
                        if not (0 <= nr < rows and 0 <= nc < cols) or (nr, nc) == obstacle:
                            nr, nc = r_idx, c_idx
                        ev += probs[i] * (0 + discount * V[nr, nc])
                    best_v = max(best_v, ev)
                new_V[r_idx, c_idx] = best_v

        V = new_V

        print(f"\n--- Iteration k={k} ---")
        print(f"Calculation Trace for Cell (0,2):")
        print(trace_math)
        print(f"Result for (0,2): {V[0, 2]:.2f}")
        print("\nGrid Values:")
        print(np.round(V, 2))

value_iteration_with_math()

Enter the number of iterations (k): 3

--- Iteration k=1 ---
Calculation Trace for Cell (0,2):
V_1(0,2) = max_a [ 0.8*(0.9*V_0(0,3)) + 0.1*(0.9*V_0(0,2)) + 0.1*(0.9*V_0(1,2)) ]
Result for (0,2): 0.00

Grid Values:
[[ 0.  0.  0.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]

--- Iteration k=2 ---
Calculation Trace for Cell (0,2):
V_2(0,2) = max_a [ 0.8*(0.9*V_1(0,3)) + 0.1*(0.9*V_1(0,2)) + 0.1*(0.9*V_1(1,2)) ]
Result for (0,2): 0.72

Grid Values:
[[ 0.    0.    0.72  1.  ]
 [ 0.    0.    0.   -1.  ]
 [ 0.    0.    0.    0.  ]]

--- Iteration k=3 ---
Calculation Trace for Cell (0,2):
V_3(0,2) = max_a [ 0.8*(0.9*V_2(0,3)) + 0.1*(0.9*V_2(0,2)) + 0.1*(0.9*V_2(1,2)) ]
Result for (0,2): 0.78

Grid Values:
[[ 0.    0.52  0.78  1.  ]
 [ 0.    0.    0.43 -1.  ]
 [ 0.    0.    0.    0.  ]]
